/* Auto-generated solutions (one move-string per level: U/D/L/R). Optimal where micro-BFS succeeded. */
(function (global) {
  'use strict';
  const SOLUTIONS = [
  "UULDDLDR",
  "UURRUDLLURURLDRDLLDDDRRULDLUUU",
  "UDLLULURDRUUUDDRDRUUURULDDDRRDLDLUUUU",
  "UUUULURRDRRDDLLDLUUURULDLLDDRDRUUURRRUL",
  "URUUUUDDDRRDLDLUUUURULDDDLLUUUDDDLDDRUUUURUL",
  "UUUUURULDDDDDDRRUUUUURULDDDLDLUUUDDLDLUUUDDDLDDRUUUU",
  "DRRUUULULLRRRDDDDLLURDRUUURULDDDDLLLLURRRDRUUULURULLL",
  "LLUURLDRRUUUURULDDDDDDRUUUUULURDDDRRDLRDLLUUUUDDDDDLUUUUU",
  "URRDLDDDLLDRDRUUUUULURRDRDLULDDDLDDRUUUUUDDDRRDLDLUUUULURRULL",
  "UUUUUDDDLLDRDRUUUULUURRDRDLULDDDLDDRUUUUULDRDDRRDLDLUUUULURRULL"
];
  global.SokobanSolutions = SOLUTIONS;
  if (typeof module !== 'undefined' && module.exports) module.exports = SOLUTIONS;
})(typeof window !== 'undefined' ? window : globalThis);
